// Initialize Supabase client
const supabaseUrl = 'https://nclewuhijsmmtuzinahi.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbGV3dWhpanNtbXR1emluYWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMDY0MDYsImV4cCI6MjA1Mjg4MjQwNn0.QrVXyYKpNQt_njuqssS95-MCcQS_qW1oUcA4zt97W6k'
const supabase = window.supabase.createClient(supabaseUrl, supabaseKey)
